name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'

  pull_request:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/kerneltoast/android_kernel_google_gs201
          kernel-dir: gs201
          kernel-branch: 15.0.0-sultan
          config: gs201_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: ""
          aosp-clang-version: r530567
          ccache: true
          disable-lto: false
          anykernel3: true
          anykernel3-url: https://github.com/EduardoA3677/AnyKernel3.git
